package User;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Guest.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class Guest extends User {

	@Override
	public void StartWorking() {
		// TODO Auto-generated method stub
		
	}
}
