package User;

import User.User;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Manager.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class Manager extends User {
	public void BookRoom() {
	}

	@Override
	public void StartWorking() {
		// TODO Auto-generated method stub
		
	}
}
