package Main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Amphitheater.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class Amphitheater extends Room {
}
