package Main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ClassicalRoom.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class ClassicalRoom extends Room {
}
