package Main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Director.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class Director extends User {
	public void EjectRoom() {
	}
	
	public void BookRoom() {
	}
}
