package Main;



//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MainRoomPlanner.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class MainRoomPlanner {
	public static void main(String[] args) {
		System.out.println("hello");
	}
}
