package Main;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Room.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class Room {
	public Object Material;
	public Object Available;
	public Object Slot;
	public User Users;
	public Object Room-size;
}
