package Main;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class User {
	public Object Name;
	public Object Surname;
	public Object Mail;
	public Object Password;
	public void JoinMeeting() {
	}
}

// 1. Créer des modules room / users