package Room;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VisioRoom.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//

public class VisioRoom extends Room {
}
