//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Collaborator.java
//  @ Date : 02/04/2020
//  @ Author : 
//
//




public class Collaborator extends User {
}
